### ISSUE TITLE
Paging: noPaging & totalRowCount

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/core#31]
- 希望能在送request的時候可以有「不要paging」的選項，也許可以是`/console/lab/reps?noPaging`之類的
- 希望response送回來的時候，在`paging`這個object裡面除了`pages`告訴我總共有幾頁之外，可以有`totalRowCount`，告訴我這個resource總共有多少row

**Comment by chihaoyo** [comment]
純粹許願，可以討論 😆

**Comment by charlieworld** [comment]
> 希望能在送request的時候可以有「不要paging」的選項，也許可以是/console/lab/reps?noPaging之類的
 這個用 /console/lab/reps?all   如何?
> 希望response送回來的時候，在paging這個object裡面除了pages告訴我總共有幾頁之外，可以有totalRowCount，告訴我這個resource總共有多少row
這個沒問題

**Comment by chihaoyo** [comment]
`/reps?all`++

**Comment by charlieworld** [comment]
更正， 應該是   /console/lab/reps?page=all

**Comment by chihaoyo** [comment]
這樣你還要判斷傳進來的page是int還是string耶？`/reps?all`不會比較優雅嗎？

**Comment by charlieworld** [comment]
不用 ?all=xxx 之類的？ 

可以直接 ?all 就好？ 

我可以試試看，如果可以的話就用 ?all

**Comment by wesley100002001** [comment]
我也是有一樣的疑問 XDD

**Comment by chihaoyo** [comment]
我記得是可以啦，不過是 `<? isset($_GET['all']) ?>` 這裡來的，記憶有點久遠ler

**Comment by chihaoyo** [comment]
@charlieworld response裡的paging object裡還可以給我`page`嗎？就是「現在這個response是哪一個page」的意思

**Comment by charlieworld** [comment]
> @charlieworld response裡的paging object裡還可以給我page嗎？就是「現在這個response是哪一個page」的意思

OK !

**Comment by chihaoyo** [comment]
@charlieworld 還有 `pageSize`：「一個page最多多少row」（目前是20對吧？）。如果有其他達成的方法也請跟我說！

**Comment by charlieworld** [comment]
pageSize 也要 0.0 ?!  沒問題  目前預設是 20

**Comment by chihaoyo** [comment]
因為前端其實無從得知`pageSize` 😆
