### ISSUE TITLE
MsgListArray 的參數

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/core#34]
現在會看到 MsgListArray (arr, pages, previous, next,reply)
應該可以包成 MsgListArray (arr, pagingObj, reply)，把跟 paging 相關的東西先包成一個 json object 再傳，避免過長的 function parameter

**Comment by charlieworld** [comment]
它現在變得更長了 XDDDD
(arr, totalRowCount, paging, pages, previous, next,reply)

的確要包成Object 沒錯 XD

應該會改成 :
( arrObj, pagingObj,reply)

**Comment by charlieworld** [comment]
已修正 :
https://github.com/watchout-tw/core/commit/94daf17a2d3189ea7f555e99b108e4b3265b4644
